### ISSUE TITLE
Create debounce event in for loop

### ISSUE THREAD

**Issue by brunohorta82** [xoseperez/debounceevent#6]
Hello master :), 

I can create debouceEvent in for loop, you know why?

`for(int i  = 0 ; i < _switchsJson.size() ; i++){ 
    DebounceEvent* a =  new DebounceEvent(4, callback, 0);
}
`

`Exception (9):
epc1=0x40209f51 epc2=0x00000000 epc3=0x00000000 excvaddr=0x070f0307 depc=0x00000000

ctx: cont 
sp: 3fff1460 end: 3fff16c0 offset: 01a0

>>>stack>>>
3fff1600:  3fff2d28 3fff2d20 00000001 40209f46  
3fff1610:  4020c0ec 3fff1630 4021b8a4 4021b884  
3fff1620:  3fff18cc 3fff2d20 3fff1648 4020c5cc  
3fff1630:  3fff1648 0000015d 000003e8 00000000  
3fff1640:  00000000 00000000 401074a8 00000000  
3fff1650:  000003e8 00000000 3fff2ca4 3fff2cfc  
3fff1660:  40107150 00000000 00000000 00000400  
3fff1670:  3fff0174 3ffe9590 3fff05d8 402190d4  
3fff1680:  0001c200 0000001c 00000000 3fff0698  
3fff1690:  3fffdad0 00000000 3fff0691 4020c62e  
3fff16a0:  feefeffe feefeffe feefeffe 4021a754  
3fff16b0:  feefeffe feefeffe 3fff06a0 40100710  
<<<stack<<<`

**Comment by xoseperez** [comment]
You want to store each instance you create on an array or vector, otherwise, you are overwriting and losing the references. It's good it fails.

```
#include <vector>
std::vector<DebounceEvent *> _objects;
for(int i = 0 ; i < _switchsJson.size() ; i++){ 
    DebounceEvent* a = new DebounceEvent(_switchsJson[i].pin, callback, 0); 
    _objects.push_back(a);
}
```

(mind the above code is not tested).
